version: '3'

services:
    services:
        build: ./example_services
        expose: 
            - 4001
            - 4002
    gateway:
        build: .
        ports:
            - 8000:80
        environment: 
            CACHE_MAX_AGE: '5'
            ENGINE_API_KEY: '...'
            # POLL_INTERVAL: 30
            URL_0: "http://services:4001"
            URL_1: "http://services:4002"